# cloudbuild.yaml
steps:
# Step 1: Build the Docker image for our Django web app
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    # This tags the image with the correct path for Artifact Registry
    - 'europe-central2-docker.pkg.dev/secret-node-420018/dockerrepochavdar/webapp:latest'
    # This tells the build to use the Dockerfile located in the 'docker' subdirectory
    - '-f'
    - 'docker/Dockerfile'
    # '.' is the build context (the entire project root)
    - '.'

# Step 2: Push the built image to our Artifact Registry
images:
  - 'europe-central2-docker.pkg.dev/secret-node-420018/dockerrepochavdar/webapp:latest'