services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONPATH: /home/django/app 
    # depends_on:
    #   - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  ml:  
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml
    env_file:
      - .env
    # depends_on:

volumes:
  pgdata: