# .github/workflows/ci.yml

name: Docker Build Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in the workspace
        run: ls -laR

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # This step has been corrected with the 'file' parameter.
      - name: Build the Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile # <-- THE FIX IS HERE
          load: true
          tags: powerbidder-image:test
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max

      - name: Run Django Tests
        run: |
          docker run --rm \
            -e SECRET_KEY="a-dummy-secret-key-for-testing" \
            -e DEBUG="False" \
            powerbidder-image:test \
            /opt/venv/bin/python manage.py test